CREATE DATABASE resume;

USE resume;

CREATE TABLE IF NOT EXISTS historico (
    id INT AUTO_INCREMENT PRIMARY KEY,
    texto LONGTEXT NOT NULL,
    resumo LONGTEXT NOT NULL,
    datahora DATETIME DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM historico;